name: Build WordleHelper Windows

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt 6.4.2
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.4.2"
          modules: "qtbase"   # use qtbase instead of qtquick
          arch: "win64_msvc"

      - name: Configure CMake
        run: cmake -B build -S . -G "Visual Studio 17 2022" -DCMAKE_PREFIX_PATH="C:\Qt\6.4.2\msvc_64"

      - name: Build
        run: cmake --build build --config Release

      - name: Deploy Qt
        run: |
          set PATH=C:\Qt\6.4.2\msvc_64\bin;%PATH%
          windeployqt --release build\Release\appWordleHelper.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WordleHelper-Windows
          path: build/Release
