name: Build WordleHelper Windows

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.4.2"
          modules: "qtquick"
          arch: "win64_msvc"   # or "win64_mingw" if you prefer

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Deploy Qt
        run: |
          set PATH=%PATH%;C:\Qt\6.4.2\msvc_64\bin
          windeployqt build\Release\appWordleHelper.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WordleHelper-Windows
          path: build/Release
